all: waveTiling clean

waveTiling: waveTiling-vignette.tex
cp -p ../inst/scripts/waveTiling-vignette.pdf .

clean:
	$(RM) -f *.out *.bbl *.log *.aux *.blg *.brf *.toc *.tex
	$(RM) -f Rplots.pdf waveTiling-*


